In [5]:
# câu 1 : Khai báo hàm numpy và in ra version 

import numpy as np
np.version.version

'1.16.2'

In [6]:
# câu 2 : Tạo mảng 1 chiều từ 0 đến 9

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# câu 3: Tạo một mảng boolean 3x3 với tất cả giá trị là True

# Cách 1 :
np.ones((3,3)) > 0
# Cách 2 : 
np.ones((3,3),dtype=bool) 
# Cách 3:
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [37]:
# câu 4 : Lấy những phần tử mà thoả mãn một điều kiện cho trước của mảng một chiều

# Tìm phần tử có giá rị lẻ 
arr = np.arange(0,10)
arr[arr%2==1]


array([1, 3, 5, 7, 9])

In [38]:
# câu 5 : Thay thế phần tử thoả mãn điều kiện cho trước bằng 1 một giá khác

# Thay thế phần tử có giá trị lẻ bằng -1
arr = np.arange(0,10)
arr[arr %2 ==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [46]:
# câu 6 : Thay thế phần tử thoả mãn điều kiện cho trước bằng 1 một giá khác 
# nhưng không thay đổi mảng ban đầu

# Thay thế tất cả số lẻ bằng giá trị -1 nhưng mảng ban đầu không thay đổi

arr = np.arange(0,10) 
print(arr)
arr_copy = arr
arr_copy[arr %2 ==1] = -1
arr_copy

# Cách 2 :
out = np.where(arr%2== 1,-1,arr)
out


[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [51]:
# câu 7 : Định dạng/chuyển mảng

# Chuyển mảng 1 chiều thành mảng 2 chiều có 2 hàng ( dòng )

arr = np.arange(10) # tạo mảng 1d gồm 10 phần tử
print(arr)
arr_2d = arr.reshape(2,-1) # -1 có ý nghìa là số cột của data_2d được tính tự động
arr_2d

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
# câu 8:  xếp chồng 2 mảng theo chiều dọc

a = np.arange(10).reshape(2,-1)
print(a)
b = np.repeat(1,10).reshape(2,-1)
print(b)

# Cách 1 : 
c= np.concatenate([a,b],axis =0)
c

# Cách 2 : 
d = np.vstack([a,b])
d

# Cách 3 : 
e = np.r_[a,b]
e

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [67]:
# câu 9 : xếp chồng 2 mảng theo chiều ngang

a = np.arange(10).reshape(2,-1)
print(a)
b = np.repeat(1,10).reshape(2,-1)
print(b)

# Cách 1 : 
c= np.concatenate([a,b],axis =1)
c

# Cách 2 : 
d = np.hstack([a,b])
d

# Cách 3 : 
e = np.c_[a,b]
e

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [82]:
# câu 10 : Tạo ra chuỗi custom không dùng hàm mã hoá

# Tạo ra mảng sau không dùng hàm mã hoá 
# chỉ dùng hàm numpy có sẵn với mảng a như bên dưới

a = np.array([1,2,3])
print(a)
np.repeat(a,3) # tạo mảng mới lặp lại mỗi phần tử lên 3 lần
np.tile(a,3) # tạo mảng mới lặp lại mảng tất cả phần tử lên 3 lần
np.hstack([np.repeat(a,3) , np.tile(a,3)]) # xếp chồng 2 mảng theo chiều ngang 

[1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [83]:
# câu 11 : Lấy phần tử chung của 2 mảng a và b 

a = np.array([1,2,3,2,3,4,3,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)



array([2, 4])

In [85]:
# câu 12 : Xoá phần tử từ 1 mảng mà tồn tại trong 1 mảng khác

# Từ mảng a xoá tất cả các phần tử mà đã có trong mảng b

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [86]:
# câu 13: Lấy tất cả vị trí nơi giá trị các phần tử của 2 mảng a,b giống nha

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a ==b)

(array([1, 3, 5, 7]),)

In [93]:
# câu 14 : Lấy tất cả các giá trị trong 1 phạm vi cho trước từ 1 mảng

a = np.array([2,6,1,9,10,3,27])

# Cách 1: tìm tất cả vi trí của các phần tử có giá trị trong phạm vi cho trước 
index = np.where((a>=5)&(a<=10))
print(index)
a[index]

#Cách 2 :
index = np.where(np.logical_and(a>=5,a<=10))
a[index]

#Cách 3: 
a[(a>=5)&(a<=10)]



(array([1, 3, 4]),)


array([ 6,  9, 10])

In [107]:
# câu 15 : Tạo hàm xử lý số vô hướng ứng dụng trên mảng numpy

# Biến đổi hàm maxx xử lý trên 2 số vô hướng để áp dụng trên 2 mảng:

def maxx(x,y):
    # Lấy số lớn nhất nhất trong 2 số
    if x >= y :
        return x
    else:
        return y
    
# numpy.vectorize lấy hàm maxx: x,y và biến nó thành maxx: a[] -> b[].
pair_max = np.vectorize(maxx,otypes=[float])

a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

pair_max(a,b)


array([6., 7., 9., 8., 9., 7., 5.])

In [109]:
# Cách 2: dùng hàm maximum
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])
np.maximum(a,b)

#Cách 3: dùng hàm where 
np.where(a > b,a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [143]:
# câu 16 : Hoán 2 cột trong mảng 2 chiều 

# Ví dụ: Hoán cột 1 và 2 trong mảng arr
arr = np.arange(9).reshape(3,3)
print(arr)
# in theo thứ tự cột 0,2,1
arr[:,[1,0,2]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [142]:
# câu 17 :  Hoán 2 hàng trong mảng 2 chiều 

# Ví dụ: Hoán dòng 1 và 2 trong mảng arr
arr = np.arange(9).reshape(3,3)
print(arr)
# in theo thứ tự cột 0,2,1
arr[[1,0,2],:]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [147]:
# câu 18 : Đoản ngược hàng trong mảng 2 chiều

arr = np.arange(9).reshape(3,3)
print(arr)
arr[::-1,]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [148]:
# câu 19 : # câu 18 : Đoản ngược cột trong mảng 2 chiều

arr = np.arange(9).reshape(3,3)
print(arr)
arr[:,::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [155]:
# Câu 20 :  Tạo mảng 2 chiều chứa số kiểu float từ 5 đến 10

# Cách 1 : Dùng hàm uniform cho kiểu float
# Tạo mảng 2 chiều 5x3 từ 5 đến 10

arr = np.random.uniform(5,10,size=(5,3)).reshape(5,3)
print(arr)

[[6.47685264 7.86244037 6.14808425]
 [8.21788856 8.30326847 5.69096852]
 [7.52502254 8.05263037 5.58540214]
 [5.49201034 6.64052277 8.07812157]
 [5.17193202 8.56214323 6.66659607]]


In [160]:
# Cách 2 : Tạo mảng 2 chiều 5x3 chứa kiểu float từ 5 đến 10 
# dùng hàm randint (số nguyên) và random (số float từ 0 đến 1) 

arr = np.random.randint(5,10,size=(5,3)) + np.random.random((5,3))
print(arr)

[[5.42979563 7.68312075 7.13231802]
 [5.30241536 6.4205596  8.08502439]
 [8.68667298 5.99197105 5.91279598]
 [6.07384813 9.10311803 8.96379223]
 [5.56598781 6.42861612 5.52049045]]


In [201]:
# câu 21 :  In mảng 2 chiều kiểu float chỉ với 3 số lẻ

# Input
rand_arr = np.random.random([5,3])
# giới hạn in 3 số lẻ 
np.set_printoptions(precision=10)
rand_arr


array([[0.8162247487, 0.274073747 , 0.4317041837],
       [0.9400298196, 0.8176493788, 0.3361119501],
       [0.1754104537, 0.3728320463, 0.0056885074],
       [0.2524263534, 0.7956625085, 0.0152549712],
       [0.5988433769, 0.603804539 , 0.1051476854]])

In [204]:
# câu 22 : Làm thế nào để in một mảng gọn gàng 
# bằng cách loại bỏ ký hiệu khoa học (như 1e10)

# Ví dụ :
# hàm seed tạo ra các số ngẫu nhiên có thể dự đoán được tức không đổi
np.random.seed(100)
print(np.random.random([3,3]))

rand_arr = np.random.random([3,3])/1e3
print(rand_arr)
# giới hạn in 6 số lẻ và suppress=True : nghĩa là loại bỏ ki hiệu toán học
np.set_printoptions(suppress=True,precision=6)
print(rand_arr)

[[0.543405 0.278369 0.424518]
 [0.844776 0.004719 0.121569]
 [0.670749 0.825853 0.136707]]
[[0.000575 0.000891 0.000209]
 [0.000185 0.000108 0.00022 ]
 [0.000979 0.000812 0.000172]]
[[0.000575 0.000891 0.000209]
 [0.000185 0.000108 0.00022 ]
 [0.000979 0.000812 0.000172]]


In [207]:
# câu 23 : Giới hạn số phần tử được in ra của mảng

a = np.arange(15)
print(a)
# threshold = 6 : nghhĩa là chỉ hiển thị 6 phần tử 
np.set_printoptions(threshold=6)
a

[ 0  1  2 ... 12 13 14]


array([ 0,  1,  2, ..., 12, 13, 14])

In [227]:
# câu 24 : In đầy đủ tất cả các số phần tử của mảng

a = np.arange(100)
print(a)
np.set_printoptions(threshold=np.inf)
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [281]:
# câu 25 : Nhập tập dữ liệu với số và văn bản 
# vẫn giữ nguyên trạng văn bản trong mảng numpy

# ví dụ : Nhập tập dữ liệu IRIS giữ nguyên trạng văn bản
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# Vì chúng ta muốn giữ nguyên các mẫu, các trường văn bản, loại dữ liệu là đối tượng(dtype=object)
# Nếu dtype = None thì mảng 1 chiều kiểu tuples sẽ được trả về
iris = np.genfromtxt(url,delimiter=',',dtype='object')
names = ('sepallength','sepalwidth','petallength','petalwidth','species')
print(names)
print(iris[:3]) # in 3 hàng đầu tiên
print(iris.shape)
iris[:5,4].shape
iris[:10,4]

('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]
(150, 5)


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa'], dtype=object)

In [296]:
# câu 26 : Trích xuất một cột cụ thể từ mảng 1 chiều của kiểu dữ liệu tuples

# Ví dụ : trích xuất cột văn bản species từ mảng iris 1D được nhập trong câu 25

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',',dtype=None)
print(iris_1d.shape) # mảng 1 chiều với 150 dòng : (150,)
print(iris_1d[:5])
# Tạo mảng 1 chiều species trích xuất từ cột 4 của mỗi phần tử trong mảng iris_1d 
species = np.array([row[4] for row in iris_1d])
species[:5]


(150,)
[(5.1, 3.5, 1.4, 0.2, b'Iris-setosa') (4.9, 3. , 1.4, 0.2, b'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, b'Iris-setosa') (4.6, 3.1, 1.5, 0.2, b'Iris-setosa')
 (5. , 3.6, 1.4, 0.2, b'Iris-setosa')]


/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

In [329]:
# câu 27 : Biến đổi mảng 1 chiều thành mảng 2 chiều 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

# Cách 1 : Biến đổi mỗi hàng thành list rồi lấy 4 phần tử đầu

irsi_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

# Cách 2 : trích xuất 4 cột đầu từ nguon URL
iris_2d = np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0,1,2,3])
iris_2d[:4]


/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  after removing the cwd from sys.path.


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [344]:
# câu 28 : Tính toán mean , median , standard deviation của 1 mảng :
# Mean (số trung bình): Trung bình số học được tính đơn giản bằng tổng của tất cả các giá trị của dữ liệu trong mẫu chia cho kích thước mẫu.
# Số trung vị (Median) là giá trị giữa trong một phân bố chia phân bố thành 2 nhóm mà trong đó số các số trong mỗi nhóm bằng nhau
# Độ lệch chuẩn (Standard Deviation) : Độ lệch chuẩn mô tả biến thiên của các cá thể trong quần thể 

# Ví dụ : Tìm giá trị trung bình, trung vị, độ lệch chuẩn 
# của cột sepallength của tập dữ liệu iris (cột thứ 1)

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
# Trích xuất cột 1 từ IRIS thành mảng 1 chiều 
sepallength = np.genfromtxt(url,delimiter=',',dtype=float,usecols=[0])
sepallength.shape
print(sepallength[:10])

# giá trị trung bình, trung vị, độ lệch chuẩn của sepallength
mea , med , sd = np.mean(sepallength) , np.median(sepallength) , np.std(sepallength)

print(mea,med,sd)

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9]
5.843333333333334 5.8 0.8253012917851409


In [352]:
# câu 29 : Normalize một mảng để các giá trị nằm trong khoảng từ 0 đến 1

# Ví dụ : Tạo một định dạng chuẩn hóa của cột sepallength iris có giá trị nằm trong khoảng từ 0 đến 1 
# sao cho mức tối thiểu có giá trị 0 và tối đa có giá trị 1.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Cách 1 : Công thức chuẩn hoá 1 mảng có giá trị từ 0 -> 1
# norm_array_a  = a(i) - min.a / ( max.a - min.a )
norm_sepallength = (sepallength - sepallength.min()) / (sepallength.max() - sepallength.min())
norm_sepallength

# Cách 2 : dùng hàm ptp() lấy phạm vi giá trị tức ( max - min ) 
norm_sepallength2 = (sepallength - sepallength.min()) / sepallength.ptp()
norm_sepallength2[:10]


array([0.222222, 0.166667, 0.111111, 0.083333, 0.194444, 0.305556,
       0.083333, 0.194444, 0.027778, 0.166667])

In [363]:
# câu 30 : Tính toán điểm softmax

# Vi dụ : Tính toán điểm softmax của cột sepallength

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
print(sepallength.shape)

def softmax(x):
    # tính giá trị softmax của từng tập điểm của x
    e_x = np.exp(x - np.max(x))
    return ( e_x / e_x.sum())

# in chỉ 3 số lẻ
np.set_printoptions(precision=3)

print(softmax(sepallength))
                 

(150,)
[0.002 0.002 0.001 0.001 0.002 0.003 0.001 0.002 0.001 0.002 0.003 0.002
 0.002 0.001 0.004 0.004 0.003 0.002 0.004 0.002 0.003 0.002 0.001 0.002
 0.002 0.002 0.002 0.002 0.002 0.001 0.002 0.003 0.002 0.003 0.002 0.002
 0.003 0.002 0.001 0.002 0.002 0.001 0.001 0.002 0.002 0.002 0.002 0.001
 0.003 0.002 0.015 0.008 0.013 0.003 0.009 0.004 0.007 0.002 0.01  0.002
 0.002 0.005 0.005 0.006 0.004 0.011 0.004 0.004 0.007 0.004 0.005 0.006
 0.007 0.006 0.008 0.01  0.012 0.011 0.005 0.004 0.003 0.003 0.004 0.005
 0.003 0.005 0.011 0.007 0.004 0.003 0.003 0.006 0.004 0.002 0.004 0.004
 0.004 0.007 0.002 0.004 0.007 0.004 0.016 0.007 0.009 0.027 0.002 0.02
 0.011 0.018 0.009 0.008 0.012 0.004 0.004 0.008 0.009 0.03  0.03  0.005
 0.013 0.004 0.03  0.007 0.011 0.018 0.007 0.006 0.008 0.018 0.022 0.037
 0.008 0.007 0.006 0.03  0.007 0.008 0.005 0.013 0.011 0.013 0.004 0.012
 0.011 0.011 0.007 0.009 0.007 0.005]


In [378]:
# câu 31 : Tìm percentile scores của mảng 

# Ví dụ : Tìm percentile thứ 5 và 95 của mảng iris cột sepallength
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

np.percentile(sepallength,q=[5,95])


array([4.6  , 7.255])

In [91]:
import numpy as np

# câu 32 : Chèn giá trị tại 1 vị trí ngẫu nhiên trong mảng

# Ví dụ : Chèn giá trị np.nan ở 20 vị trí ngẫu nhiên trong tập dữ liệu iris_2d

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# Cách 1 : 
i,j = np.where(iris_2d) # lấy index của số hàng , số cột của 600 phần tử của mảng ( 150,5)
np.random.seed(100)
# np.random.choice : tạo 1 mẫu ngẫu nhiên từ mảng 1 chiều cho trước

iris_2d[np.random.choice((i),20) , np.random.choice((j),20)] = np.nan

# Cách 2 : 
np.random.seed(100)
iris_2d[np.random.randint(150,size=20),np.random.randint(4,size=20)] = np.nan
print(iris_2d[:10])



[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' nan b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [107]:
# câu 33 : Tìm vị trí của không có giá trị trong mảng numpy

# Tìm số lượng và vị trí của các phần tử không có giá trị trong sepallength của iris_2d (cột thứ 1)

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
# np.isnan(iris_2d[:, 0]) : tìm phần tử không có giá trị , 0 là cột 1 của mảng iris_2d 
print("Số lượng các phần tử không có giá trị: \n", np.isnan(iris_2d[:, 0]).sum())
print("Vị trí của các phần tử không có giá trị: \n", np.where(np.isnan(iris_2d[:, 0])))


Số lượng các phần tử không có giá trị: 
 6
Vị trí của các phần tử không có giá trị: 
 (array([13, 36, 38, 61, 68, 93]),)


In [118]:
# câu 34 : Lọc một mảng numpy dựa trên hai hoặc nhiều điều kiện

# Ví dụ : Lọc các hàng iris_2d có petallength (cột thứ 3)> 1.5 và sepallength (cột thứ 1) <5.0

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

iris_2d[:5]
condition = (iris_2d[:,2] > 1.5 ) & (iris_2d[:,0] < 5.0)
iris_2d[condition]


array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [135]:
# câu 35 : Loại các hàng có chứa một giá trị bị thiếu từ một mảng numpy

# Ví dụ: chọn các hàng trong mảng iris_2d không có giá trị nan.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Cách 1: tìm trên toàn mảng
condition = np.all(np.isnan(iris_2d),axis = 1) # axis = 1 : trục hàng ngang 
iris_2d[~condition][:5] # kí hiệu ~ : nghĩa là lấy phủ định

# Cách 2: tìm từng hàng trên mảng
any_nan_in_row = np.array([np.any(np.isnan(row)) for row in iris_2d]) 
iris_2d[~any_nan_in_row][:5]



array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [154]:
# câu 36 : Tìm mối tương quan giữa hai cột của một mảng

# Ví dụ : Tìm mối tương quan giữa SepalLength (cột thứ 1) và PetalLength (cột thứ 3)

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#Cách 1 : dùng hàm corrcoef 
np.corrcoef(iris_2d[:,0],iris_2d[:,2])[0,1]

#Cách 2: dùng hàm pearsonr
from scipy.stats.stats import pearsonr 
pearsonr(iris_2d[:,0],iris_2d[:,2])[0]

# corrcoef chỉ mức độ quan hệ tuyến tính giữa hai biến số, phạm vi từ -1 đến +1


0.8717541573048712

In [165]:
# câu 37 : Tìm xem một mảng đã cho có chứa bất kỳ giá trị rỗng nào không

# Ví dụ : 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.isnan(iris_2d).any()

False

In [179]:
# câu 38 : Thay thế tất cả các phần tử thiếu giá trị bằng 0 trong một mảng numpy

# Ví dụ : Thay thế tất cả các phần tử chứa nan bằng 0 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

iris_2d[np.isnan(iris_2d)] =0
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [193]:
# câu 39 : Tìm số lượng các giá trị duy nhất trong một mảng numpy

# Ví dụ : Tìm các giá trị duy nhất và số lượng các giá trị duy nhất trong cột species

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

#Cách 1: dùng hàm unique
np.unique(iris[:,4],return_counts=True)

#Cách 2: rút trích 1 mảng species từ cột 4 của màng iris 
# và lấy giá trị duy nhất và đếm só lượng

species = np.array([row.tolist()[4] for row in iris])

np.unique(species,return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'), array([50, 50, 50]))

In [255]:
# câu 40 : Chuyển đổi số thành một mảng phân loại theo định dạng văn bản

#Ví dụ :  Chuyển đổi cột 3 petallength thành mảng văn bản như sau : 
# Nhỏ3 hơn 3 --> 'small'
# Từ 3->5    --> 'medium'
# Lớn hơn 5  --> 'large'

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# hàm np.digitize : trả về vị trí chỉ số của bin mà mỗi phần tử thuộc khoảng bin tương ứng
bin_petallength = np.digitize(iris[:,2].astype(float),[0,3,5,10]) # chuyển đổi mảng sang mảng bin tương ứng với bảng định nghĩa chuyển đổi 
# ánh xạ bảng bin thành văn bản tương ứng
label_map = {1:'small',2:'medium',3:'large',4:np.nan}
             
map_bin_petallength = [label_map[x] for x in bin_petallength ]

map_bin_petallength[:8]

['small', 'small', 'small', 'small', 'small', 'small', 'small', 'small']

In [258]:
np.max(iris[:,2])

b'6.9'

In [308]:
# câu 41 : Tạo một cột mới từ các cột hiện có của một mảng

#Ví dụ : Tạo một cột mới , 
# trong đó giá trị mỗi phần tử là (pi x petallength x sepal_length ^ 2) / 3


url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Rút trích cột petallength x sepal_length
sepallength = iris_2d[:,0].astype('float')
petallength = iris_2d[:,2].astype('float')

new_col = (np.pi * petallength * (sepallength**2))/3
# Định dạng cột mới cùng số chiều  với iris_2d
new_col = new_col[:,np.newaxis]
# Thêm cột mới vào iris_2d dùng hàm hstack
result = np.hstack([iris_2d,new_col])
result[:5]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa',
        36.65191429188092]], dtype=object)

In [380]:
# câu 42 : Lấy mẫu xác suất trong numpy

# Lấy mẫu ngẫu nhiên cột species của mảng iris 
# sao cho trị setose gấp đôi số lượng của versicolor và virginica
# np.unique(iris[:,4],return_counts=True)
# Lấy cột species từ iris
species = iris_2d[:,4]

#Cách 1:  Tạo xác suất với Iris-setosa(50%),Iris-versicolor(25%),Iris-virginica(25%)
# dùng hàm choice
np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a,150,p=[0.5,0.25,0.25])

#Cách 2:  lấy mẫu xác suất 
np.random.seed(100)
# Tạo 50 số  từ 0->0.5 , 50 số  từ 0.5->0.75 , 50 số  từ 0.75->1.0 thàng 1 mảng 150 số :
probs = np.r_[np.linspace(0,0.500,num=50),np.linspace(0.501,0.750,num=50),np.linspace(0.751,1.0,num=50)]
# Lấy ngẫu nhiên mảng gồm 150 chỉ số từ mảng xac suất probs gồm  
index = np.searchsorted(probs,np.random.random(150))
# Tạo mẫu cần tìm dược lấy từ mảng pecies với index sau khi searchsorted
species_out = species[index]
print(np.unique(species_out,return_counts=True))

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object), array([77, 37, 36]))


In [401]:
# câu 43 :  Tìm giá trị lớn thứ hai của một mảng khi được nhóm bởi một cột/mảng khác.

#Ví dụ : Tìm giá trị lớn thứ hai của petallength của cột species được nhóm theo setosa


url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Tạo mảng mới nhóm bởi giá trị setosa

setosa = iris[iris[:, 4] == b'Iris-setosa']

# Chỉ lấy cột 2 rồi chuyển thành kiểu float

petal_len_setosa = setosa[:,2]

# Lấy giá trị lớn thứ hai của mảng :

np.unique(np.sort(petal_len_setosa))[-2]

b'1.7'

In [404]:
# câu 44 : Sắp xếp một mảng 2D theo một cột

# Ví dụ : Sắp xếp tập dữ liệu iris dựa trên cột sepallength 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Sắp xếp cột 0 (SepalLength) 
iris[iris[:,0].argsort()][:10]

array([[b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'3.0', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.5', b'2.3', b'1.3', b'0.3', b'Iris-setosa'],
       [b'4.6', b'3.6', b'1.0', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'4.6', b'3.2', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [416]:
# câu 45 : Tìm giá trị xuất hiện nhiều nhất trong mảng

# Ví dụ : Tìm giá trị thường xuyên nhất trong cột petallength (cột thứ 3) trong tập dữ liệu iris.
# Lấy các phần tử duy nhất và số lượng mỗi phần tử
values , counts = np.unique(iris[:,2],return_counts = True)

# Dùng hàm np.argmax để tìm vi trí của phần tử xuát hiện nhiều nhất
print(values[np.argmax(counts)])

b'1.5'


In [441]:
# câu 46 : Tìm vị trí xuất hiện đầu tiên của một giá trị lớn hơn một giá trị đã cho

# Ví dụ : Tìm vị trí xuất hiện đầu tiên của một giá trị lớn hơn 1.0 trong cột thứ 4 (petalwidth)
# của tập dữ liệu iris.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
# Lấy cột thứ 4 petalwidth và định dạng kiểu float thoã lớn hơn 1 
petalwidth = iris[:,3].astype('float') > 1
# Hàm argwhere lấy index của mảng thoã điều kiên cho trước
np.argwhere(petalwidth)[0]



array([50])

In [451]:
# câu 47 : Thay thế tất cả các giá trị lớn hơn một giá trị cho trước thành một phạm vi cho trước

# Ví dụ : Thay thế tất cả các giá trị lớn hơn 30 thành 30 và dưới 10 thành 10
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50,20)
print(a)

# Cách 1 : dùng hàm np.clip sẽ thay thế giá trị nhỏ hơn min thành min
# giá trị lớn hơn max thành max 
np.clip(a,a_min=10,a_max=30)

# Cách 2 : dùng hàm np.where(condition, [x, y])
print(np.where(a < 10, 10 , np.where(a > 30, 30,a)))


[27.63 14.64 21.8  42.39  1.23  6.96 33.87 41.47  7.7  29.18 44.67 11.25
 10.08  6.31 11.77 48.95 40.77  9.43 41.   14.43]
[27.63 14.64 21.8  30.   10.   10.   30.   30.   10.   29.18 30.   11.25
 10.08 10.   11.77 30.   30.   10.   30.   14.43]


In [128]:
# câu 48 : Lấy vị trí của n giá trị đứng đầu từ một mảng numpy

# Ví dụ : Lấy vị trí của 5 giá trị lớn nhấttrong một mảng a

np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(a)

# Cách 1 : dùng hàm np.argsort() xuất mảng index của các phần tử sau khi sắp xếp từ thấp lên cao
# rồi lấy 5 vi trí cuối 
print('Vị trí : ',np.argsort(a)[-5:])
print('Giá trị : ',a[np.argsort(a)[-5:]])

# Cách 2 : dùng hàm sort() 
print('Vị trí : ',np.argpartition(a,-5)[-5:])
print('Giá trị : ', a[np.argpartition(a,-5)[-5:]])




[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
Vị trí :  [18  7  3 10 15]
Giá trị :  [40.99501269 41.466785   42.39403048 44.67477576 48.95256545]
Vị trí :  [18  7  3 10 15]
Giá trị :  [40.99501269 41.466785   42.39403048 44.67477576 48.95256545]


In [217]:
# câu 49 : Tính tổng theo hàng của tất cả các giá trị xuất hiện có trong một mảng

# Ví dụ : Tính tổng các giá trị duy nhất theo hàng.
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
print(arr)

def counts_of_all_values_rowwise(arr2d):
    # Tìm các già trị duy nhất và tổng từng giá trị theo hàng
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]

    # Tính tổng tất cả giá trị theo hàng
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

print(np.arange(1,11))
counts_of_all_values_rowwise(arr)

# Ví dụ 2 : 
arr = np.array([np.array(list('bill clinton')), np.array(list('narendramodi')), np.array(list('jjayalalitha'))])
print(arr)
print(np.unique(arr))
counts_of_all_values_rowwise(arr)


[[ 9  9  4  8  8  1  5  3  6  3]
 [ 3  3  2  1  9  5  1 10  7  3]
 [ 5  2  6  4  5  5  4  8  2  2]
 [ 8  8  1  3 10 10  4  3  6  9]
 [ 2  1  8  7  3  1  9  3  6  2]
 [ 9  2  6  5  3  9  4  6  1 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[['b' 'i' 'l' 'l' ' ' 'c' 'l' 'i' 'n' 't' 'o' 'n']
 ['n' 'a' 'r' 'e' 'n' 'd' 'r' 'a' 'm' 'o' 'd' 'i']
 ['j' 'j' 'a' 'y' 'a' 'l' 'a' 'l' 'i' 't' 'h' 'a']]
[' ' 'a' 'b' 'c' 'd' 'e' 'h' 'i' 'j' 'l' 'm' 'n' 'o' 'r' 't' 'y']


[[1, 0, 1, 1, 0, 0, 0, 2, 0, 3, 0, 2, 1, 0, 1, 0],
 [0, 2, 0, 0, 2, 1, 0, 1, 0, 0, 1, 2, 1, 2, 0, 0],
 [0, 4, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 1, 1]]