### Arrays

Một mảng numpy là một lưới tập hợp các giá trị cùng kiểu dữ liệu và được đánh số bằng các số nguyên dương. Số chiều(trục) được gọi là hạng (rank) của mảng; chiều(shape) của mảng là một kiểu tuple các số nguyên dương chỉ kích cỡ của mảng theo mỗi chiều.

Ta khởi động mảng numpy từ nested Python lists, và truy xuất đến các phần tử dùng dấu ngoặc vuông:

In [0]:
import numpy as np

a = np.array([1, 2, 3]) # Tạo một numpy array với rank = 1

print(type(a))            # Sẽ in ra "<class 'numpy.ndarray'>"
print(a.shape)            # Sẽ in ra "(3,)"
print(a[0], a[1], a[2])   # Sẽ in ra "1 2 3"
a[0] = 5                  # Thay đổi giá trị của 1 phần tử trong mảng
print(a)                  # Sẽ in ra kết quả là "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Tạo một numpy array với rank =2
print(b.shape)                     # In ra "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Sẽ in ra "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


### Numpy cũng cung cấp rất nhiều hàm để khởi tạo mảng

In [0]:
import numpy as np

a = np.zeros((2,2))   # Tạo một numpy array với tất cả phẩn tử là 0
print(a)              # "[[ 0.  0.]
                      #   [ 0.  0.]]"

b = np.ones((1,2))    # Tạo một numpy array với tất cả phẩn tử là 1
print(b)              # "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Tạo một mảng hằng
print(c)               # "[[ 7.  7.]
                       #   [ 7.  7.]]"

d = np.eye(2)         # Tạo một ma trận đơn vị 2 x 2
print(d)              # "[[ 1.  0.]
                      #   [ 0.  1.]]"

e = np.random.random((2,2))  # Tạo một mảng với các giá trị ngẫu nhiên
print(e)       

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.95300191 0.02064703]
 [0.14603527 0.0898466 ]]


### Array indexing

Numpy cung cấp một số cách để truy xuất phần tử trong mảng

Slicing: Tương tự như kiểu danh sách(list) trong python, mảng numpy cũng có thể được cắt. Vì mảng có thể nhiều chiều, nên bạn phải chỉ việc cắt cho mỗi chiều của mảng.

In [0]:
import numpy as np
 
# Khởi tạo numpy array có shape = (3, 4) có giá trị như sau:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [0]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [0]:
# Sử dụng slicing để tạo mảng b bằng cách lấy 2 hàng đầu tiên
# và cột 1, 2. Như vậy b sẽ có shape = (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

In [0]:
b

array([[2, 3],
       [6, 7]])

In [0]:
# Việc 1 mảng mới được tạo ra từ slicing sẽ có cùng địa chỉ với mảng gốc.
# Nếu thay đổi 1 trong 2 thì mảng còn lại cũng thay đổimảng theo.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] ở đây tương đương với a[0, 1]
print(a[0, 1])   # Prints "77"

2
77



Bạn cũng có thể kết hợp việc dùng slicing và dùng chỉ số. Tuy nhiên, cách làm đó sẽ cho ra một mảng mới có rank thấp hơn mảng gốc. Chú ý rằng điều này hoàn toàn khác từ cái cách MATLAB xử lý mảng slicing


In [0]:
import numpy as np
 
# Tạo một numpy array có shape (3, 4) với giá trị như sau:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
 
# Hai cách truy cập dữ liệu ở hàng giữa của mảng
# Dùng kết hợp chỉ số và slice -> được array mới có rank thấp hơn,
# Nếu chỉ dùng slice ta sẽ có 1 array mới có cùng rank với array gốc

row_r1 = a[1, :]    # Rank 1, hàng thứ 2 của a
row_r2 = a[1:2, :]  # Rank 2, vẫn là hàng thứ 2 của a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"
 

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [0]:
# Chúng ta có thể làm tương tự với cột của numpy array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**Integer array indexing:** Khi bạn truy xuất mảng dùng slicing, kết quả trả về sẽ là mảng con của mảng ban đầu, tuy nhiên sử dụng chỉ số mảng cho phép bạn xây dựng mảng tùy ý từ một mảng khác, ví dụ: 

In [0]:
import numpy as np
 
a = np.array([[1,2], [3, 4], [5, 6]])
 
# Một ví dụ của truy xuất mảng dùng chỉ số.
# Kết quả thu được là 1 mảng có shape (3,)
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"
 
# Sẽ thu được kết quả tương đương như trên với cách này:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# Khi sử dụng chỉ số mảng bạn được phép truy xuất tới 1 phần tử của mảng gốc nhiều hơn 1 lần
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"
 
# Một cách làm khác tương đương:
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


**Một mẹo hữu ích dùng chỉ số mảng để chọn và thay đổi phần tử từ mỗi hàng của ma trận**

In [0]:
import numpy as np

# Tạo một mảng mới từ đó ta sẽ chọn các phần tử
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Tạo một mảng các chỉ số
b = np.array([0, 2, 0, 1])

# Lấy 1 phần tử từ mỗi hàng của mảng a dùng với chỉ số ở mảng b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Thay đổi một phẩn tử từ mỗi hàng của a dùng với chỉ số ở mảng b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]



**Boolean array indexing:** Cho phép bạn chọn ra các phần tử tùy ý của một mảng, thường được sử dụng kiểu truy xuất này để chọn ra các phần tử thỏa mãn điều kiện nào đó, ví dụ :

In [0]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

print(a)

bool_idx = (a > 2)   # Tìm các phần tử lớn hơn 2;
                     # Trả về 1 mảng boolean có chiều như mảng a
                     # và giá trị tại mỗi phần tử là 
                     # True nếu phần tử của a tại đó > 2,
                     # False cho trường hợp ngược lại.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [0]:
# Ch1ng ta sử dụng boolean array indexing để  xây dựng mảng 1 chiều 
# bao gồm các phần tử tương ứng với giá trị True của bool_dix
# Ví dụ ở đây in ra các giá trị của a > 2 , sử dụng array bool_idx đã tạo
print(a[bool_idx])  # Prints "[3 4 5 6]"

# Một cách ngắn gọn hơn:
print(a[a > 2])     # Prints "[3 4 5 6]"

[3 4 5 6]
[3 4 5 6]


### Kiểu dữ liệu (Datatypes)


Mỗi mảng numpy là một lưới các phần tử cùng kiểu dữ liệu. Numpy cung cấp một tập hợp lớn các kiểu dữ liệu số mà bạn có thể sử dụng để xây dựng các mảng. Numpy cố gắng đoán một kiểu dữ liệu khi bạn tạo một mảng, nhưng các hàm xây dựng các mảng thường cũng bao gồm một đối số tùy chọn để chỉ định rõ ràng kiểu dữ liệu, ví dụ : 

In [0]:
import numpy as np

x = np.array([1, 2])   # Để tự numpy xác định kiểu dữ liệu
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Để tự numpy xác định kiểu dữ liệu
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Chỉ định kiều dữ liệu củ thể cho mảng
print(x.dtype)                         # Prints "int64"

int64
float64
int64


### Phép toán trên mảng(Array Math)

Các hàm toán cơ bản hoạt động trên từng nguyên tố của mảng và có cả toán tử nạp chồng và nhu hàm trong module numpy:

In [0]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Tổng của 2 mảng, cả 2 cách cho cùng một kết quả
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Hiệu 2 mảng
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Tính tích từng phần tử của x nhân với từng phần tử của y
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Tương tự thương của từng phần x chia với từng phần tử y
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Căn bậc 2 từng phần tử trong x
print(np.sqrt(x))       # [[ 1.          1.41421356]
                        #  [ 1.73205081  2.        ]]



[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


**Lưu ý:** rằng không giống như MATLAB, `*` là phép nhân theo từng phần tử, không phải là phép nhân ma trận. Thay vào đó, chúng ta sử dụng hàm dot để tính các thành phần bên trong của vectơ, để nhân một vectơ với ma trận và nhân ma trận với ma trận. Hàm dot có sẵn cả dưới dạng một hàm trong mô đun numpy và như một phương thức của đối tượng mảng:

In [0]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Tích trong của 2 vector; Cả 2 đều cho kết quả là 219
print(v.dot(w))
print(np.dot(v, w))

# Nhân ma trận với vector; cả 2 đều cho mảng rank 1: [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Ma trận với ma trận; cả 2 đều cho mảng rank 2
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy cung cấp nhiều hàm hữu ích để thực hiện tính toán trên mảng; một trong những hàm hữu ích nữa là **sum**

In [0]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Tổng các phần tử của mảng; prints "10"
print(np.sum(x, axis=0))  # Tính tổng theo từng cột; prints "[4 6]"
print(np.sum(x, axis=1))  # Tính tổng theo từng hàng; prints "[3 7]"

10
[4 6]
[3 7]


Bạn có thể tìm thấy danh sách đầy đủ các hàm toán học được cung cấp bởi numpy tại đây [documentation](https://docs.scipy.org/doc/numpy/reference/routines.math.html)

Ngoài việc tính toán trên mảng, chúng ta thường xuyên phải định hình lại hoặc thao tác dữ liệu theo mảng. Ví dụ đơn giản nhất của loại hoạt động này là chuyển vị ma trận; để chuyển vị một ma trận, chỉ cần sử dụng thuộc tính T của một đối tượng mảng

In [0]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Việc chuyển vị 1 mảng có rank = 1 không thay đổi gì cả:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


**Broadcasting**
Broadcasting là một cơ chế mạnh mẽ cho phép thực thi các phép toán số học trên các numpy array có kích thước khác nhau. Thường, chúng ta  có một mảng nhỏ hơn và một mảng lớn hơn và chúng tôi muốn sử dụng mảng nhỏ hơn nhiều lần để thực hiện một số thao tác trên mảng lớn hơn.

Ví dụ: Giả sử rằng chúng ta muốn thêm một vectơ không đổi vào mỗi hàng của ma trận. Chúng ta có thể làm như thế này: 


In [0]:
import numpy as np

# Chúng ta sẽ thêm vector v vào mỗi hàng của ma trận x,
# Lưu trữ kết quả trong ma trận y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Tạo một ma trận rỗng có shape như x

# Thêm vector v vào mỗi hàng của ma trận x bằng một vòng lặp
for i in range(4):
    y[i, :] = x[i, :] + v

# Ma trận y sẽ như sau
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Cách này hoạt động bình thường, khi ma trận x quá lớn, việc sử dụng vòng lặp này sẽ rất chậm. Nếu bạn để ý thì việc thêm vectơ v vào mỗi hàng của ma trận x tương đương với việc tạo một ma trận vv bằng cách xếp chồng nhiều bản sao của v theo chiều dọc, sau đó thực hiện phép tính tổng của x và vv. Chúng ta có thể thực hiện phương pháp này như thế này

In [0]:
import numpy as np

# Chúng ta sẽ thêm vector v vào mỗi hàng của ma trận x,
# Lưu trữ kết quả trong ma trận y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Xếp chồng 4 bản sao của v lên nhau
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Thực hiện phép cộng
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting cho phép chúng ta thực thi tính toán này mà không cần phải tạo ra nhiều bản sao của v. Và đây là code khi sử dụng broadcasting

In [0]:
import numpy as np

# Chúng ta sẽ thêm vector v vào mỗi hàng của ma trận x,
# Lưu trữ kết quả trong ma trận y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Thêm v vào từng hàng của x sử dụng broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Dòng y = x + v hoạt động ngay cả khi x có hình chiều (4, 3) và v có chiều (3,); nhờ vào broadcasting mà dòng này hoạt động như thể vecto v thực sự có chiều (4, 3), trong đó mỗi hàng là một bản sao của v và tổng được thực hiện theo từng phần tử.

Broadcasting cho  hai mảng với nhau theo các quy tắc sau:

- Nếu các mảng không có cùng thứ hạng, hãy thêm vào hình dạng của mảng thứ hạng thấp hơn với 1s cho đến khi cả hai hình có cùng độ dài.
- Hai mảng được cho là tương thích về mặt số chiều nếu chúng có cùng kích thước trong từng chiều  hoặc nếu một trong các mảng có kích thước bằng 1 trong chiều đó.
- Các mảng có thể được broadcasting cùng nhau nếu chúng tương thích ở tất cả các chiều.
- Sau khi broadcasting, mỗi mảng hoạt động như thể nó có chiều bằng với tối đa số chiều của hai mảng đầu vào.
- Trong bất kỳ chiều nào, khi một mảng có kích thước 1 và mảng khác có kích thước lớn hơn 1, mảng đầu tiên hoạt động như thể nó được sao chép dọc theo chiều của mảng lớn hơn.

Nếu lời giải thích này chưa rõ, hãy thử đọc lời giải thích từ [tài liệu](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

Các chức năng hỗ trợ broadcasting được gọi là các chức năng phổ biến. Bạn có thể tìm thấy danh sách tất cả các chức năng phổ quát trong [tài liệu](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Dưới đây là một vài ứng dụng của broadcasting :

In [9]:
import numpy as np

# Tính tích của hai vecto
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# Trước tiên, ta phải định hình vecto v thành vecto cột với chiều (3,1)
# Sau đó, ta broadcast v với w để có được ma trận (3,2) chính là tích của v và w
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Cộng một vecto vào mỗi hàng của ma trận:
x = np.array([[1,2,3], [4,5,6]])
# x có chiều là  (2, 3) và v có chiều là (3,) 
# Sau khi broadcast sẽ thành ma trận  (2, 3) :
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Cộng một vecto vào mỗi hàng của ma trận :
# x có chiều là  (2, 3) và w có chiều là (2,)
# Chuyển vị x sẽ được hiều (3, 2) và broadcast với w cho ra mảng với chiều (3,2)
# Sau đó , chuyển vị kết quả này , ta có ma trận cuối cùng là (2,3):
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Một cach khác là định dạng chiều w thành một vecto cột (2,1)
# Sau đó, ta broadcast w với x để tạo ra cùng kết quả :
print(x + np.reshape(w, (2, 1)))

# Nhân ma trận với một hằng số:
# x có chiều (2, 3). Numpy xử lý số vô hướng như mảng có số chiều rỗng;
# sau đó , broadcast sẽ tạo ra ma trận (2, 3) như sau :
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


**SciPy**
Numpy provides a high-performance multidimensional array and basic tools to compute with and manipulate these arrays. SciPy builds on this, and provides a large number of functions that operate on numpy arrays and are useful for different types of scientific and engineering applications.

The best way to get familiar with SciPy is to browse the documentation. We will highlight some parts of SciPy that you might find useful for this class.

Numpy cung cấp một mảng đa chiều hiệu suất cao và các công cụ cơ bản để tính toán và thao tác với các mảng này. SciPy xây dựng dựa trên điều này và cung cấp một số lượng lớn các hàm mà  hoạt động trên các mảng numpy và rất hữu ích cho các loại ứng dụng khoa học và kỹ thuật khác nhau.

Cách tốt nhất để làm quen với SciPy là duyệt [tài liệu](http://docs.scipy.org/doc/scipy/reference/index.html). Chúng tôi chỉ giới thiệu một số phần của SciPy mà bạn có thể thấy hữu ích.

**Xử lý hình ảnh (Image operations)**
SciPy provides some basic functions to work with images. For example, it has functions to read images from disk into numpy arrays, to write numpy arrays to disk as images, and to resize images. Here is a simple example that showcases these functions:

SciPy cung cấp một số hàm cơ bản để làm việc với hình ảnh. Ví dụ,  hàm đọc hình ảnh từ đĩa thành mảng, ghi  mảng  vào đĩa dưới dạng hình ảnh và để thay đổi kích thước hình ảnh. Dưới đây là một ví dụ đơn giản giới thiệu các chức năng này:



In [10]:
from scipy.misc import imread, imsave, imresize

# Read an JPEG image into a numpy array
img = imread('assets/cat.jpg')
print(img.dtype, img.shape)  # Prints "uint8 (400, 248, 3)"

# We can tint the image by scaling each of the color channels
# by a different scalar constant. The image has shape (400, 248, 3);
# we multiply it by the array [1, 0.95, 0.9] of shape (3,);
# numpy broadcasting means that this leaves the red channel unchanged,
# and multiplies the green and blue channels by 0.95 and 0.9
# respectively.
img_tinted = img * [1, 0.95, 0.9]

# Resize the tinted image to be 300 by 300 pixels.
img_tinted = imresize(img_tinted, (300, 300))

# Write the tinted image back to disk
imsave('assets/cat_tinted.jpg', img_tinted)

ImportError: ignored

**Khoảng cách giữa các điểm(Distance between points)**

SciPy định nghĩa một số hàm hữu ích để tính toán khoảng cách giữa các tập điểm.

Hàm scipy.spatial.distance.pdist tính khoảng cách giữa tất cả các cặp điểm trong một tập hợp đã cho:



In [11]:
import numpy as np
from scipy.spatial.distance import pdist, squareform

# Create the following array where each row is a point in 2D space:
# [[0 1]
#  [1 0]
#  [2 0]]
x = np.array([[0, 1], [1, 0], [2, 0]])
print(x)

# Compute the Euclidean distance between all rows of x.
# d[i, j] is the Euclidean distance between x[i, :] and x[j, :],
# and d is the following array:
# [[ 0.          1.41421356  2.23606798]
#  [ 1.41421356  0.          1.        ]
#  [ 2.23606798  1.          0.        ]]
d = squareform(pdist(x, 'euclidean'))
print(d)

[[0 1]
 [1 0]
 [2 0]]
[[0.         1.41421356 2.23606798]
 [1.41421356 0.         1.        ]
 [2.23606798 1.         0.        ]]
